{% set name = "pydeck-earthengine-layers" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8dca91867fdd843d590eea412a93b6715fd67f7573a414cce4da7aa08d57bdc3

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - earthengine-api
    - jinja2
    - pip
    - pydeck
    - python
    - requests
    - setuptools
    - twine
  run:
    - earthengine-api
    - pydeck
    - jinja2
    - python
    - requests

test:
  imports:
    - pydeck_earthengine_layers

about:
  home: https://github.com/UnfoldedInc/earthengine-layers/tree/master/py
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Pydeck wrapper for use with Google Earth Engine
  doc_url: https://earthengine-layers.com/
  dev_url: https://github.com/UnfoldedInc/earthengine-layers/tree/master/py

extra:
  recipe-maintainers:
    - kylebarron
